#!/bin/sh
#
# Script zum synchronisieren von Serien auf den Pi
#
# Einzelne Serien Staffeln
# sowie
# aktuelle Folgen von woechentlich ausgetrahlten Serien
#
# 0.1 Initial release - 2014/09/23
# 0.2 Added case - 2014/09/23
#
#
#

# Variablendeklaration
target="/mnt/rpiseries"
source="/media/d3c21c66-af4b-41d4-b098-462e83fa641d/Serien"
age="-14"
files="/tmp/rsyncfiles"

# Check ob das Mountverzeichnis exisitert
if [ ! -d "$target" ]; then
	mkdir "$target"
fi

# Funktion zum mounten des Verzeichnisses in das lokale Dateisystem via NFS
mountRPi () {
	echo "Checking if Directory is already mounted..."
	if [ `stat -fc%t:%T "$target"` != `stat -fc%t:%T "$target/.."` ]; then
		echo "$target is already mounted!"
	else
		echo "$target is not mounted."
		echo "Mounting Directory now..."
		mount 192.168.178.66:/export/Serien/Serien "$target"
		echo "Directory mounted successfully!"
	fi
}

# Funktion zum unmounten des Verzeichnisses
umountRPi () {
	echo "Unmounting Directory now..."
	umount "$target"
	echo "Directory unmounted successfully!"
}

# Funktion zum auflisten der Dateien nicht aelter als X Tage
collectFiles () {
	echo "Changing directory..."
	cd "$source"
	echo "Directory changed. Searching for files that where modified within the last 14 days..."
	find . -mtime "$age" > "$files"
	echo "Files collected."
}

# Funktion zum synchronisieren der woechentlichen Serien
syncFiles () {
	echo "Syncing files now..."
	rsync -Ravh --files-from="$files" . "$target"
	echo "Files synced successfully!"
}

collectSeason () {
#	echo "Writing Season with correct path to $files"
	#example: find . -name "Scrubs*""*S04*"
#	cd "$source"
#	find . -name \"$2\"\"$3\" > "$files"
	echo $2
	echo $3
#	cat "$files"
}

#syncSeason () {
	#content
#}

case $1 in
	season)
#		mountRPi
#		mkdir "$target"/"$3" -p
#		rsync -rv --relative "$2" "$target"/"$4"
#		umountRPi
		collectSeason
	;;

	sync)
		mountRPi
		collectFiles
		syncFiles
		umountRPi
	;;

	mount)
		mountRPi
	;;

	umount)
		umountRPi
	;;

	*)
		echo "pisync called with unknown argument"
		echo "Syntax: pisync season|sync arguments"
		echo "Example: pisync season \"Season Folder\" \"target location (Series/Season Folder)\" \"Series Title\""
		exit 1
	;;
esac

exit 0
