#!/bin/sh
#
# Script zum synchronisieren von Serien auf den Pi
#
# Einzelne Serien Staffeln
# sowie
# aktuelle Folgen von woechentlich ausgetrahlten Serien
#
# 0.1 Initial release - 2014/09/23
# 0.2 Added case - 2014/09/23
#
#
#

# Variablendeklaration
target="/mnt/rpiseries"
source="/media/UUID/Serien"
age="-14"
files="/tmp/rsyncfiles"

# Check ob das Mountverzeichnis exisitert
if [ ! -d /mnt/rpiseries ]; then
	mkdir /mnt/rpiseries
fi

# Funktion zum mounten des Verzeichnisses in das lokale Dateisystem via NFS
mountRPi () {
	echo "Mounting Directory now..."
	mount 192.168.178.66:/export/Serien/Serien /mnt/rpiseries
	echo "Directory mounted successfully!"
}

# Funktion zum unmounten des Verzeichnisses
umountRPi () {
	echo "Unmounting Directory now..."
	umount "$target"
	echo "Directory unmounted successfully!"
}

# Funktion zum auflisten der Dateien nicht aelter als X Tage
collectFiles () {
	echo "Changing directory..."
	cd "$source"
	echo "Directory changed. Searching for files that where modified within the last 14 days..."
	find . -mtime "$age" > "$files"
	echo "Files collected."
}

# Funktion zum synchronisieren der woechentlichen Serien
syncFiles () {
	echo "Syncing files now..."
	rsync -Ravh --files-from="$files" . "$target"
	echo "Files synced successfully!"
}

case $1 in
	season)
		mountRPi
		mkdir "$target"/"$3" -p
		rsync -rv --relative "$2" "$target"/"$4"
		umountRPi
	;;

	sync)
		mountRPi
		collectFiles
		syncFiles
		umountRPi
	;;

	*)
		echo "pisync called with unknown argument" >&2
		echo "Syntax: pisync season|sync arguments"
		echo "Example: pisync season \"Season Folder\" \"target location (Series/Season Folder)\" \"Series Title\""
		exit 1
	;;
esac

exit 0
